name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential ccache git openjdk-17-jdk unzip zip libffi-dev libssl-dev libsqlite3-dev liblzma-dev zlib1g-dev libncurses5-dev libtinfo5
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: myapp-apk
          path: bin/*.apk
